--- !Ups

--- !create table "people" (
  --- !"id" bigint generated by default as identity(start with 1) not null primary key,
  --- !"name" varchar not null,
  --- !"age" int not null
--- !);


--- !Downs

--- !drop table "people" if exists;

# --- !Ups
CREATE TABLE Todo (
    id bigint(20) NOT NULL AUTO_INCREMENT,
    name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    PRIMARY KEY (id)
);


INSERT INTO Todo values (1,'Shopping list','Grocery: eggs,tomatoes,soy sauce', 'DONE');
INSERT INTO Todo values (2,'Dorm Fee','7,759 THB before 30 Jul', 'PENDING');
INSERT INTO Todo values (3,'Travel Notes','toothbrush,towel,chargers', 'PENDING');

# --- !Downs

DROP TABLE Todo;